param(
  [switch]$Push
)

try {
  $workspace = Split-Path -Parent $MyInvocation.MyCommand.Path
} catch {
  Write-Error "Unable to determine script path. Run the script from its folder."
  exit 1
}

$jsonPath = Join-Path $workspace '.copilot_memory.json'
$statusJsonPath = Join-Path $workspace 'project_status.json'
$statusMdPath = Join-Path $workspace 'PROJECT_STATUS.md'

# Load memory if exists
$memory = $null
if (Test-Path $jsonPath) {
  try { $memory = Get-Content $jsonPath -Raw | ConvertFrom-Json } catch { $memory = $null }
}

# Gather Git info
Push-Location $workspace
$gitBranch = ''
$lastCommit = ''
$gitStatus = ''
try {
  $gitBranch = (& git rev-parse --abbrev-ref HEAD) -replace "\r|\n",""
  $lastCommit = (& git log -1 --pretty=format:'%h %ad %s' --date=iso) -replace "\r|\n",""
  $gitStatus = (& git status --porcelain) -join "`n"
} catch {
  Write-Host "Git command failed or this is not a git repository. Skipping git details."
}

# Compose status object
$status = [ordered]@{
  timestamp = (Get-Date).ToString('o')
  workspace = $workspace
  git = [ordered]@{
    branch = $gitBranch
    last_commit = $lastCommit
    status = $gitStatus
  }
  memory_summary = $null
}

if ($null -ne $memory) {
  $status.memory_summary = [ordered]@{
    memory_count = (($memory.memory_points) | Measure-Object).Count
    last_updated = $memory.last_updated
    top_items = ($memory.memory_points | Select-Object -First 5 | ForEach-Object { @{ id = $_.id; title = $_.title } } | ConvertTo-Json -Depth 5)
  }
}

# Write JSON status
$status | ConvertTo-Json -Depth 10 | Set-Content -Path $statusJsonPath -Encoding utf8

# Write human-readable status
$md = @()
$md += "# Project Status"
$md += "- Timestamp: $($status.timestamp)"
$md += "- Workspace: $($status.workspace)"
if ($gitBranch) { $md += "- Git branch: $gitBranch" }
if ($lastCommit) { $md += "- Last commit: $lastCommit" }
if ($gitStatus) {
  $md += "- Git status summary:"
  $md += '```'
  $md += $gitStatus
  $md += '```'
}
if ($null -ne $status.memory_summary) {
  $ms = $status.memory_summary
  $md += "- Memory points: $($ms.memory_count)"
  $md += "- Memory last updated: $($ms.last_updated)"
}
$md += ""
$md += "---"
$md += 'Generated by update_status.ps1.'
$md -join "`n" | Set-Content -Path $statusMdPath -Encoding utf8

# Commit status files
try {
  & git add (Split-Path $statusJsonPath -Leaf) (Split-Path $statusMdPath -Leaf) 2>$null
  $statusOutput = & git status --porcelain
  if (-not [string]::IsNullOrWhiteSpace($statusOutput)) {
    & git commit -m "Auto-update project status: $((Get-Date).ToString('s'))" 2>$null
    if ($LASTEXITCODE -eq 0) { Write-Host "Committed project status snapshot." }
    else { Write-Host "Git commit failed. Check repo config." }
    if ($Push) {
      & git push
      if ($LASTEXITCODE -ne 0) { Write-Host "Push failed; check remote/auth." } else { Write-Host "Pushed project status to remote." }
    }
  } else {
    Write-Host "No changes to commit for project status."
  }
} catch {
  Write-Host "Git operations skipped or failed: $_"
} finally {
  Pop-Location
}

Write-Host "Status update complete: $statusJsonPath"
